data:
  eval_dir:  /media/liulei/Data/cityscapes
  save_dir: /media/liulei/Data/checkpoints/mask/eval
  dataset: cityscapes
  batch_size: 1
  input_size: (512, 1024)
  num_classes: -1
  subset: val

seed: 1
compound_coef: 3
model_type: fcos
anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
weights_path: /home/liulei/下载/fcos_weights_00000005.pth
weights_dir: #/home/liulei/PycharmProjects/instance-segmentation-mask/weights
decode_cfg_path: ./configs/decode_cfg.yaml
trans_cfg_path: ./configs/trans_cfg.json
metrics: ['box', 'instance']
