data:
  test_dir: /media/liulei/Data/cityscapes/leftImg8bit/test
  test_image:
  save_dir: /media/liulei/Data/checkpoints/fcos_mask/test
  dataset: dir
  batch_size: 1
  input_size: (512, 1024)
  num_classes: 9

seed: 1
compound_coef: 3
model_type: fcos
anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
weights_path: /home/liulei/下载/fcos_weights_00000036.pth
decode_cfg_path: ./configs/decode_cfg.yaml
trans_cfg_path: ./configs/trans_cfg.json
