data:
  test_dir: /media/liulei/Data/dataset/bigdata/carImages/train/image
  test_image:
  save_dir: /media/liulei/Data/checkpoints/bigdata/test
  dataset: dir
  batch_size: 1
  input_size: (512, 1024)
  num_classes: 11

seed: 1
compound_coef: 3
model_type: eff
anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
weights_path: /media/liulei/Data/checkpoints/bigdata/eff_weights_00000076.pth
decode_cfg_path: ./configs/decode_cfg.yaml
trans_cfg_path: ./configs/trans_cfg.json
